package com.dianping.cricket.dal.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation for table id corresponding class property.
 * @author tenglinxiao
 * @since 0.0.1
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface Id {
	// value means the id field defined in table.
	public String value() default "ID";
	// indicate whether the id is auto generated.
	public boolean autoGenerated() default true;
}
